version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tomez
    container_name: tomez-app
    depends_on:
      - postgres
      - nginx
    ports:
      - "3001:3000"
    networks:
      - tomez-network
  postgres:
      image: postgres:17
      container_name: tomez-postgres
      environment:
        POSTGRES_USER: samy
        POSTGRES_PASSWORD: root
        POSTGRES_DB: tomez
      expose:
      - "5432"
      volumes:
        - ./database/data:/var/lib/postgresql/data
        - ./database/init-scripts:/docker-entrypoint-initdb.d
      networks:
        - tomez-network
  nginx:
    image: nginx:latest
    container_name: tomez-nginx
    ports:
     - "8080:80"
    volumes:
      - "C:/Users/samy0/OneDrive/Manga:/usr/share/nginx/html/mangas:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

networks:
  tomez-network:
   
    