version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-tomez
    ports:
      - "8080:80"
    volumes:
      - "C:/Users/samy0/OneDrive/Manga:/usr/share/nginx/html/mangas:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

networks:
  tomez-network:
    external: true

volumes:
  mysql-data:
    external: true
    